const list = [
    {
      key: 1,
      title: "My First Book of Pencil Control",
      author: "Wonder House Books",
      description:"25 April 2018",
      price: 89,
      img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 2,
      title: "108 Panchatantra Stories",
      author: "Maple Press",
      description:"1 September 2020",
      price: 98,
      img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 3,
      title: "Amazing Questions & Answers Science",
      author: "Editorial Team",
      description:"25 November 2018",
      price: 143,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 4,
      title: "My First Book of Pencil Control",
      author: "Wonder House Books",
      description:"25 April 2018",
      price: 57,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 5,
      title: "My First 1000 Words",
      author: "Wonder House Books",
      description:" 1 January 2018",
      price: 149,
      img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 6,
      title: "101 Panchatantra Stories for Children",
      author: "Editorial Team",
      description:'9 September 2020',
      price: 135,
      img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 7,
      title: "Pre-School Activities Pack ",
      author: "Editorial Team",
      description:'1 January 2021',
      price: 693,
      img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 8,
      title: "Early Learning Library Pack 1",
      author: "Wonder House Books",
      description:'6 December 2020',
      price: 289,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 9,
      title: "Blossom Moral Story Book for Kkeys ",
      author: "Content Team",
      description:'6 April 2020',
      price: 80,
      img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 10,
      title: "Brain Activity Book for Kkeys",
      author: "Maple Press",
      description:'1 September 2021',
      price: 86,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 11,
      title: "Willy the Silly Panda",
      author: "Rebecca Smith",
      description:'14 December 2021',
      price: 120,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 12,
      title: "Grandma's Bag of Stories",
      author: "Sudha Murty",
      description:' 1 January 2015',
      price: 157,
      img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 13,
      title: "My First Book of Pencil Control",
      author: "Wonder House Books",
      description:"25 April 2018",
      price: 89,
      img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 14,
      title: "108 Panchatantra Stories",
      author: "Maple Press",
      description:"1 September 2020",
      price: 98,
      img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 15,
      title: "Amazing Questions & Answers Science",
      author: "Editorial Team",
      description:"25 November 2018",
      price: 143,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 16,
      title: "My First Book of Pencil Control",
      author: "Wonder House Books",
      description:"25 April 2018",
      price: 57,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 17,
      title: "My First 1000 Words",
      author: "Wonder House Books",
      description:" 1 January 2018",
      price: 149,
      img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 18,
      title: "101 Panchatantra Stories for Children",
      author: "Editorial Team",
      description:'8 September 2020',
      price: 135,
      img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 19,
      title: "Pre-School Activities Pack ",
      author: "Editorial Team",
      description:'1 January 2021',
      price: 693,
      img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 20,
      title: "Early Learning Library Pack 1",
      author: "Wonder House Books",
      description:'6 December 2020',
      price: 289,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 21,
      title: "Blossom Moral Story Book for Kkeys ",
      author: "Content Team",
      description:'6 April 2020',
      price: 80,
      img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 22,
      title: "Brain Activity Book for Kkeys",
      author: "Maple Press",
      description:'1 September 2021',
      price: 86,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 23,
      title: "Willy the Silly Panda",
      author: "Rebecca Smith",
      description:'14 December 2021',
      price: 120,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 24,
      title: "Grandma's Bag of Stories",
      author: "Sudha Murty",
      description:' 1 January 2015',
      price: 157,
      img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 25,
      title: "Amazing Questions & Answers Science",
      author: "Editorial Team",
      description:"25 November 2018",
      price: 143,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 26,
      title: "My First Book of Pencil Control",
      author: "Wonder House Books",
      description:"25 April 2018",
      price: 57,
      img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 27,
      title: "My First 1000 Words",
      author: "Wonder House Books",
      description:" 1 January 2018",
      price: 149,
      img: "https://m.media-amazon.com/images/I/71O-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 28,
      title: "101 Panchatantra Stories for Children",
      author: "Editorial Team",
      description:'3 September 2020',
      price: 135,
      img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 29,
      title: "Pre-School Activities Pack ",
      author: "Editorial Team",
      description:'1 January 2021',
      price: 693,
      img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      key: 30,
      title: "Early Learning Library Pack 1",
      author: "Wonder House Books",
      description:'6 December 2020',
      price: 289,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
];

export default list;